--- 
title: "ToneMarks's website" 
output: 
        html_document: 
                theme: cosmo
                toc: true 
                toc_depth: 3 
                toc_float: true 
                highlight: monochrome
---
## About

My name is Antonio Marks. I've been working on courses from leanpub trying to learn how to gather and analyze data.I'm 18 years old and just graduating high school. My 5 year plans are to go to college and major in a degree of business. My love of music compels me to break into music production and/or maybe songwriting. I'm a very analytical person and is always collecting mental data so me and data science kinda go hand in hand. 

## Interests
 
* I read a lot of books when i was younger and because of this , i have an interest in anything involving reading. It's one of my strong suits.
* I feel like i have a great ability to write and so i love to read over other people's work and move/change things around to make them sound better or have maximum appeal
* I have an interest in things related to music. I like hearing people's craft and i feel like mostly anything involvong music will keep my attention
 
## Projects
 
* https://github.com/tonemarks/my_first_project.git
* https://github.com/tonemarks/antoniomarks.github.com.git
* https://github.com/tonemarks/Sample_1.git
* https://github.com/tonemarks/data_tidying_project.git
* https://github.com/tonemarks/dataviz_project.git
 
## Profiles 
 
* [tonemarks](http://github.com/tonemarks)
 
## Contact
 
* [marksantonio12@gmail](mailto:marksantonio12@gmail.com)